version: "3.9"
services:
  app:
    build:
      context: app
  mysql:
    image: mysql:8
    restart: always
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: example
  postgres:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_PASSWORD: rootpass
      POSTGRES_DB: example

